### ISSUE TITLE
GIVE CREDITS to original owner 

### ISSUE THREAD

**Issue by leviathanaxeislit** [UNGALILORUVEN/SRM_CRACKED_CODES#1]
I think GPL mandates it or i might have to dmca this repo

**Comment by Ovenoboyo** [comment]
Stop stealing. This is why this country never progresses 🙏 Jai modi

**Comment by ritik-gupta** [comment]
DMCA strike soon
jaago grahak jaago!!

**Comment by aashishdamrait** [comment]
> Stop stealing. This is why this country never progresses

`

> Jaago Grahak Jaago

`

**Comment by aashishdamrait** [comment]
> Stop stealing. This is why this country never progresses

**### Jaago Grahak Jaago**

**Comment by aashishdamrait** [comment]
> Stop stealing. This is why this country never progresses

_**Jaago Grahak Jaago**_

**Comment by spacelord16** [comment]
jago grahk jago

**Comment by itsVedant** [comment]
jaago grahak jaago. These aren't you own codes, you must give credits to original contributor.

**Comment by UNGALILORUVEN** [comment]
we are sorry about issue we have unfornately tagged ur whole repo/or part
of coding
thats why you have raised a issue on this repo
 regrets for this issue ..
 and we have del your tagging rapport part of code
 or else if you want your git hub id/owner credits  to be tagged
  in you part of your code in our repo
  .
  .and
  .
  dm again
  .
  .
  if you have some favor in helping us to build this elab session
  answer to clear the practicle examination.

sorry for the in convenience friends
